### ISSUE TITLE
Loading Gltf model

### ISSUE THREAD

**Issue by sumeshpandit** [ThomasGorisse/sceneform-android-sdk#117]
I am not able to load those models that dosen't contain animations. If a model contains animations, it loads perfectly otherwise it loads weirdly like size of model increases very very very large. Pls check this with any of your sample models which do not contain any kind of animations.

**Comment by sumeshpandit** [comment]
@ThomasGorisse

**Comment by ThomasGorisse** [comment]
Provide your glb or screenrecord if you want help.

**Comment by sumeshpandit** [comment]
> Provide your glb or screenrecord if you want help.

[https://drive.google.com/file/d/1Tu0P_9mX5FQyXIg6Atxdk9-adpnQHsJN/view?usp=sharing](https://drive.google.com/file/d/1Tu0P_9mX5FQyXIg6Atxdk9-adpnQHsJN/view?usp=sharing)

Pls try this.

**Comment by ThomasGorisse** [comment]
I only have access to your .gltf not related files. Send glb or share the entire folder.

**Comment by sumeshpandit** [comment]
> I only have access to your .gltf related files. Send glb or share the entire folder.

https://drive.google.com/file/d/1Ag8tKrgs9c1HnbuW_SOFpiT2SSdIe3XI/view?usp=sharing
@ThomasGorisse

**Comment by sumeshpandit** [comment]
@ThomasGorisse Pls ignore this. It's been resolved. Thanks for being available.
