### ISSUE TITLE
How to download this repository and use it as an external library?

### ISSUE THREAD

**Issue by iAmJuan550** [ThomasGorisse/sceneform-android-sdk#119]
Hi. I want to download this repository and use it as an external library. The reason is so that I can modify it for my own specific project. Can you tell me what changes I need to make to settings.gradle and build.gradle to be able to do that? For the open source Sceneform archive, the instructions were like [this](https://github.com/google-ar/sceneform-android-sdk#getting-started-with-sceneform-1160)

Can you provide similar instructions for using this repository as an external library in my project?

**Comment by RGregat** [comment]
The process is not that different. 
Compared to the original Repository **sceneform** is now **core** and **sceneformux** is **ux**. I can tell you tomorrow more, but yeah only the names have changed.

**Comment by RGregat** [comment]
* Download or clone this Repository and put it into your root project folder
* Modify **settings.gradle**

```groovy
include ':core'
project(':core').projectDir=new File('sceneform-android-sdk/core')

include ':ux'
project(':ux').projectDir=new File('sceneform-android-sdk/ux')
```

* Modify your **app build.gradle**

```groovy
api project(":ux")
```

* Sync everything
* You can verify if the **ux** and **core** module are added to your project by going to `File -> Project Structure -> Modules`, **ux** and **core** should be listed.

**Comment by iAmJuan550** [comment]
Thank you very much, it worked!

**Comment by agGitHub** [comment]
I am struggling to add 'Sceneform Maintained' in an existing project. 

Questions:

1) should not you add also :
