### ISSUE TITLE
Why is the anchor node disabled when its anchor is no longer tracking?

### ISSUE THREAD

**Issue by iAmJuan550** [ThomasGorisse/sceneform-android-sdk#120]
Hello. I am using Sceneform to create a large-scale augmented reality experience. I notice that when the anchor is not being tracked, the anchor node renderable and the renderable for all the children on the anchor node is disabled. This sometimes causes a weird situation where the anchor and items hosted on it start blinking (ARCore loses tracking and regains it on and off).

Is it necessary to disable the rendering of the anchors and AR items on it? Doesn't really make sense and only takes you out of a seamless augmented reality experience when it happens.

For now, I have commented out the interior of the following function:
```
private void setChildrenEnabled(boolean enabled) {
    List<Node> children = getChildren();
    for (int i = 0; i < children.size(); i++) {
      Node child = children.get(i);
      child.setEnabled(enabled);
    }
  }
```

**Comment by ThomasGorisse** [comment]
Hi,

Can you send a less then 10Mb Screenrecord here to see what's happening?

Please also paste your AugmentedImage TrackingState and TrackingMethod checks here.

**Comment by RGregat** [comment]
A video would be nice. 
Are sure that it is only your Anchor or maybe the camera which is not tracking anymore?

**Comment by iAmJuan550** [comment]
I guess I should investigate other things that might be interfering. For now, I am closing this issue.
