### ISSUE TITLE
do i have to install Google Play for AR to run it on my device?

### ISSUE THREAD

**Issue by naufalnibros** [ThomasGorisse/sceneform-android-sdk#122]
do I have to install https://play.google.com/store/apps/details?id=com.google.ar.core to run it on my device?
My device isn't compatible :(

![image](https://user-images.githubusercontent.com/22633622/126034209-43264038-5306-4b1d-948c-6fc2b6e33a3e.png)

**Comment by ThomasGorisse** [comment]
Hi.
You can still disable the AR part and use it as a 3D rendering view (see SceneView sample) but you can't use it in an AR context without ARCore Services installed.

**Comment by grassydragon** [comment]
Hi, @naufalnibros!
You can download the AR services from here https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.25.0 and install them manually. This way you can try running AR applications if your phone isn't in the list of supported devices.

**Comment by grassydragon** [comment]
Actually, I have Motorola G7 Play that is in the list of supported devices but now has the same message in Google Play. I was able to install the newest version by myself. Unfortunately, Filament crashes so it isn't possible to run Sceneform applications.

**Comment by naufalnibros** [comment]
I solved this problem thank you @ThomasGorisse  @grassydragon
