### ISSUE TITLE
Extremely laggy on Pixel 4a. The original Sceneform SDK ran smoothly!

### ISSUE THREAD

**Issue by iAmJuan550** [ThomasGorisse/sceneform-android-sdk#124]
Why is your library lagging so much? I tried  on Pixel 4a and Oneplus 6 and had terrible performance. I have depth mode enabled

**Comment by iAmJuan550** [comment]
I disabled depth mode and now the performance is quite better. I ran ARCore app with depth mode and experienced no lag whatsoever. So, there must be a problem with how you are using depth in this library.

**Comment by ThomasGorisse** [comment]
No time to loose for this.

**Comment by iAmJuan550** [comment]
> No time to loose for this.

Huh? What does that mean?
