### ISSUE TITLE
Model is getting rotated on vertical walls.

### ISSUE THREAD

**Issue by ShankarKakumani** [ThomasGorisse/sceneform-android-sdk#127]
I am using ViewRenderable to Display a poster on a Vertical wall. As soon I take the model onto a vertical wall, The model is getting rotated. 

I want the model to look the same on both the horizontal and vertical plane,

**Comment by ThomasGorisse** [comment]
```java
if (plane.getType() == Type.VERTICAL) {
    Vector3 anchorUp = anchorNode.getUp();
    andy.setLookDirection(Vector3.up(), anchorUp);
}
```
[More infos](https://github.com/google-ar/sceneform-android-sdk/issues/65#issuecomment-394798554)

**Comment by ShankarKakumani** [comment]
andy is a node or a Renderable model?

**Comment by ThomasGorisse** [comment]
See edited comment
