### ISSUE TITLE
Hiding footprint?

### ISSUE THREAD

**Issue by miftahulbagusp** [ThomasGorisse/sceneform-android-sdk#138]
How to hide or remove footprint and feature points after few seconds from detected plane?

**Comment by RGregat** [comment]
Feature Points shouldn't be visible at all. The footprint and I assume you mean the white dots on the ground, can be enabled and disabled at any time.

```java
// Disable the Plane finding. This is more or less the only thing which can be 
// changed during an ongoing session.
Session session = mArFragment.getArSceneView().getSession();
if (session == null)
    return;
Config config = session.getConfig();
config.setPlaneFindingMode(Config.PlaneFindingMode.DISABLED);
session.configure(config);
```

```java
// Toggle the visibility of the Plane-Renderable
arSceneView.getPlaneRenderer().setEnabled(false);
```

To optimize the performance for the Plane-Renerable you can do the following

```java
arSceneView
    .getPlaneRenderer()
    .setShadowReceiver(false);
arSceneView
    .getPlaneRenderer()
    .setPlaneRendererMode(PlaneRenderer.PlaneRendererMode.RENDER_TOP_MOST);
```

**Comment by miftahulbagusp** [comment]
> Feature Points shouldn't be visible at all. The footprint and I assume you mean the white dots on the ground, can be enabled and disabled at any time.
> 
> ```java
> // Disable the Plane finding. This is more or less the only thing which can be 
> // changed during an ongoing session.
> Session session = mArFragment.getArSceneView().getSession();
> if (session == null)
>     return;
> Config config = session.getConfig();
> config.setPlaneFindingMode(Config.PlaneFindingMode.DISABLED);
> session.configure(config);
> ```
> 
> ```java
> // Toggle the visibility of the Plane-Renderable
> arSceneView.getPlaneRenderer().setEnabled(false);
> ```
> 
> To optimize the performance for the Plane-Renerable you can do the following
> 
> ```java
> arSceneView
>     .getPlaneRenderer()
>     .setShadowReceiver(false);
> arSceneView
>     .getPlaneRenderer()
>     .setPlaneRendererMode(PlaneRenderer.PlaneRendererMode.RENDER_TOP_MOST);
> ```

Ok. It is working well. Thanks.
