### ISSUE TITLE
Is it possible to add environment lighting?

### ISSUE THREAD

**Issue by miftahulbagusp** [ThomasGorisse/sceneform-android-sdk#139]
In google filament, we can add environment lighting by using KtxLoader. Is it possible in Sceneform too? If so, how?

**Comment by RGregat** [comment]
I guess not, this should be a related issue to this topic: https://github.com/ThomasGorisse/sceneform-android-sdk/issues/77

**Comment by ThomasGorisse** [comment]
Work in progress...
