### ISSUE TITLE
AR Activity crashes in the first frame update on some device models

### ISSUE THREAD

**Issue by Ibrahimjo** [ThomasGorisse/sceneform-android-sdk#145]
Hi, first of all, thanks for the great work you guys are doing.
I have an activity that's responsible for starting an AR session and display a 3D object. Everything was working fine, but suddenly the activity started to crash on the first frame update (onUpdate function) with the following exception printed:

```
E/Filament: Error opening trace file: No such file or directory (2)
I/native: I0824 21:59:33.048375    5292 session.cc:3320] Update Frame Delay to 0 frames.
E/libEGL: Invalid file path for libcolorx-loader.so
E/Parcel: Reading a NULL string not supported here.
I/native: I0824 21:59:33.741704    5549 logger.h:28] DataSourceMetrics: kFirstGlCallback: 1.015956458s
E/NativeImageStreamCallback: Failed to get image metadata
    java.util.concurrent.TimeoutException: Waited 60 milliseconds (plus 924062 nanoseconds delay) for fnj@7413b69[status=PENDING, info=[inputFuture=[fne@31679ee[status=PENDING]], remaining delay=[9928 ms]]]
        at fkt.get(PG:50)
        at com.google.ar.infrastructure.nativedatasource.imagesubsystem.NativeImageStreamCallback.a(PG:9)
        at eku.onImageAvailable(PG:16)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:819)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:254)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
    Process: com.XXX.XXX, PID: 5292
    java.lang.IllegalArgumentException: Unrecognized auto exposure mode: 126
        at eio.d(PG:7)
        at dsj.f(PG:17)
        at dwm.a(PG:14)
        at hpt.i(PG:7)
        at hoo.a(PG:1)
        at hgz.e(PG:3)
        at hkz.run(PG:14)
        at hpx.f(PG:1)
        at hpw.run(PG:7)
E/NativeImageStreamCallback: Failed to get image metadata
    java.util.concurrent.TimeoutException: Waited 60 milliseconds (plus 453073 nanoseconds delay) for fnj@240bb52[status=PENDING, info=[inputFuture=[fne@20eee23[status=PENDING]], remaining delay=[9935 ms]]]
        at fkt.get(PG:50)
        at com.google.ar.infrastructure.nativedatasource.imagesubsystem.NativeImageStreamCallback.a(PG:9)
        at eku.onImageAvailable(PG:16)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:819)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:254)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

onCreate function 
```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setTheme(R.style.AR);
        setContentView(R.layout.activity_ar);
        getSupportFragmentManager().addFragmentOnAttachListener(this);
        if (savedInstanceState == null) {
            if (Sceneform.isSupported(this)) {
                getSupportFragmentManager().beginTransaction()
                        .add(R.id.fragmentar, ArFragment.class, null)
                        .commit();
            }
        }
    }
```

I followed this repository's instructions about how to add onUpdate listener and onSessionConfigurationListener, didn't add anything to the session configs.

Please note that it's working fine on Samsung, Huawei, and Xiaomi devices, but crashes on Realme devices. To be specific Realme 8 pro Android 11
The Android Studio version is 4.1.2
Google ARCore version is 1.26.0
Sceneform version 1.19.4

**Comment by ThomasGorisse** [comment]
It looks like an ARCore 1.26.0 issue on `Session` Image reading.
I reported the issue on the ARCore Github: https://github.com/google-ar/arcore-android-sdk/issues/1282

Thanks for your feedback

**Comment by devbridie** [comment]
Could you comment on the device's fingerprint: `adb shell getprop ro.build.fingerprint`? Can you repro with the official [hello_ar_java](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/hello_ar_java)?

**Comment by Ibrahimjo** [comment]
@devbridie  The device fingerprint: realme/RMX3081/RMX3081L1:11/RKQ1.201112.002/1615210778380
Yes, I can reproduce this issue with the official sample.
In fact, I managed to overcome this issue now by clearing the data of Google Play Services for AR. After clearing its data, it works for multiple times then crashes again with the same exception. I know it's just a workaround, hope that this issue gets fixed ASAP.
I'm using the latest version of Google Play Service for AR, which is: 1.26.212010383

**Comment by devbridie** [comment]
Since it repros in the official sample, I propose closing this issue and continuing in https://github.com/google-ar/arcore-android-sdk/issues/1282. I'm requesting somebody with this device to take a look now.

**Comment by Ibrahimjo** [comment]
@devbridie OK. One last thing I want to highlight, this issue is reproducible even with ARCore 1.25.0. I Tried to downgrade ARCore for Android from 1.26.0 to 1.25.0 and the issue still exists.

**Comment by ThomasGorisse** [comment]
Thanks.
I will follow it on the ARCore repo and close here when it's fixed.

**Comment by Ibrahimjo** [comment]
@ThomasGorisse  In this case I will reopen this issue and wait for you, Thanks.

**Comment by devbridie** [comment]
My understanding is that this has been resolved in a configuration push; could you verify that this is the case? Thanks.

**Comment by Ibrahimjo** [comment]
@ThomasGorisse @devbridie Yes, it has. Thanks
