### ISSUE TITLE
Screen flickering during render - Augmented Image Demo

### ISSUE THREAD

**Issue by D-Lav** [ThomasGorisse/sceneform-android-sdk#148]
First, I want to thank you guys for developing and maintaining this project.

I tried migrating my current Sceneform 1.15 project to this version. After some tweaking everything worked but I noticed screen flickering when rendering 3D models. I played with the configurations but it didn't help. I tried the Augmented Image Demo and I'm getting the same issue (see video). 

Tested with:
Google Pixel 4A (Android 11)
Sceneform Version: 1.19.6

The pixel device is new (2 days old) and only AR play services and the AR apps are installed.
When I run my project using 1.15 the issue is not occuring. The flickering can also occur when no model is rendered, although it happens less frequently.

https://user-images.githubusercontent.com/32882318/130969799-171ba26a-0b77-447e-97b5-4086e254df2e.mov

**Comment by RGregat** [comment]
@D-Lav pls recheck the hotfix branch.

**Comment by RGregat** [comment]
I reverted back to the old implementation for an ExternalTexture. Maybe my implementation of the new way is not correct 

```java
this.surface = null;

        this.filamentTexture = new Texture
                .Builder()
                .importTexture(textureId)
                .width(width)
                .height(height)
                .sampler(Texture.Sampler.SAMPLER_EXTERNAL)
                .format(Texture.InternalFormat.RGB8)
                .build(EngineInstance.getEngine().getFilamentEngine());

        SurfaceTexture surfaceTexture = new SurfaceTexture(0);
        surfaceTexture.detachFromGLContext();
        this.surfaceTexture = surfaceTexture;

        filamentStream = new Stream.Builder()
                .stream(surfaceTexture)
                .build(EngineInstance.getEngine().getFilamentEngine());

        filamentTexture.setExternalStream(
                EngineInstance.getEngine().getFilamentEngine(),
                filamentStream);

        ResourceManager.getInstance()
                .getExternalTextureCleanupRegistry()
                .register(this, new CleanupCallback(filamentTexture, filamentStream));
```

Old way

```java
surfaceTexture = null;
        surface = null;

        // Create the filament stream.
        Stream stream =
                new Stream.Builder()
                        .stream(textureId)
                        .width(width)
                        .height(height)
                        .build(EngineInstance.getEngine().getFilamentEngine());

        initialize(stream);
```

@D-Lav pls recheck.

**Comment by D-Lav** [comment]
Yes can confirm, there is no flickering using the old implementation @RGregat.
