### ISSUE TITLE
Can we use .anim files from Unity?

### ISSUE THREAD

**Issue by iAmJuan550** [ThomasGorisse/sceneform-android-sdk#162]
I have access to some .anim files created in Unity3d, can they be used with this?

**Comment by ThomasGorisse** [comment]
You have to pack them on a glb

**Comment by iAmJuan550** [comment]
Can you provide an example of how to do this? A link to a doc maybe?

**Comment by grassydragon** [comment]
I don't know about any automated way to do this. If the animations isn't very complex, you can open the model in Blender and recreate the animations from Unity by hand. Finally, you should export the model in glTF format with the animations. It would be easier if the animations were imported in Unity from an FBX file.

**Comment by iAmJuan550** [comment]
I guess this is something I will discuss with the animator in my team. Thank you all for responding.
