### ISSUE TITLE
Why are some classes and methods missing?

### ISSUE THREAD

**Issue by symbarh** [ThomasGorisse/sceneform-android-sdk#17]
Missing AugmentedFaceNode, SkeletonNode
Missing method ConfigFilter.setFacingDirection(CameraConfig.FacingDirection facing)

**Comment by ThomasGorisse** [comment]
If you have some time, you can try to merge it from here : [https://github.com/ThomasGorisse/sceneform-android-sdk/tree/v1.15.0/sceneformux/ux/src/main/java/com/google/ar/sceneform/ux](https://github.com/ThomasGorisse/sceneform-android-sdk/tree/v1.15.0/sceneformux/ux/src/main/java/com/google/ar/sceneform/ux)
and make a pull request.

**Comment by ThomasGorisse** [comment]
@symbarh Waiting for your Pull Request on that
