### ISSUE TITLE
How to properly delete a node from the scene?

### ISSUE THREAD

**Issue by iAmJuan550** [ThomasGorisse/sceneform-android-sdk#170]
The documentation is very confusing. I Googled and a lot of answers say that I should do: node.setParent(null) but others say doing that is not enough and I have to do parentOfNode.removeChild(node) to complete the process. Which one is the right way?

**Comment by ThomasGorisse** [comment]
Documentation here: [Remove or Hide a node](https://thomasgorisse.github.io/sceneform-android-sdk/remove_node)

## Remove an AnchorNode from the Scene
```kotlin
anchorNode.anchor = null
```
**Does this:**
- Disable the AnchorNode repositioning every Anchor position update
- Remove itself and all it child Nodes from the Scene = setParent(null)
- Disable/Stop rendering itself and all it child Nodes = setEnable(false)

## Remove a Model Node, VideoNode, AugmentedFaceNode,... from the Scene
```kotlin
node.parent = null
```
**OR** (do the same thing)
```kotlin
parentNode.removeChild(node)
```
**Both does this:**
- Remove himself and all it child Nodes from the Scene
- Disable/Stop rendering himself and all it child Nodes = setEnable(false)

## Show/Hide a Node = Don't render it
```kotlin
node.enabled= false
```
**Does this:**
- Disable/Stop rendering himself and all it child Nodes = setEnable(false)

## Destroy a Model Node = free renderable resources
```kotlin
node.renderableInstance.destroy()
```

**Comment by iAmJuan550** [comment]
Thank you very much, this solved my issue
