### ISSUE TITLE
java.lang.AssertionError: Unable to create RenderableInstance

### ISSUE THREAD

**Issue by cyberhenoch** [ThomasGorisse/sceneform-android-sdk#20]
Thomas thanks for taking over the project!
I believe I'm encountering the issue described here with several older versions and 1.18.5 too:
https://github.com/google-ar/sceneform-android-sdk/issues/857
https://github.com/google-ar/sceneform-android-sdk/issues/472

Any help how to solve this would be apreciated.

- When crashing I have no memory peaks, no CPU peaks (as measured by Android Studio Profiler). The app is CPU intensive though.
- Sometimes it happens with a lot of objects on the scene (100+) sometimes a few (5) is enough to crash. The objects are ViewRenderables (textview + some icons) and some basic shapes created by sceneform (ShapeFactory.makeSphere, ShapeFactory.makeCube)
- It happens only with new renderable when it is supposed to be drawn
- On some devices (Galaxy S20) the error happens much more often than others (Galaxy S10)
- After reducing viewRenderable resolutions and removing shapes, just leaving ViewRenderables it happens much less frequently but still sometimes the app crashes.

Do you have any idea how to diagnose it?
If something went wrong can we recreate the renderable instead of crashing?

My log is like this

```
…
03-18 11:31:00.888 29447 29447 D RenderabelInternalData: total:11,43 GB / free:5,03 GB / used:6,40 GB(55%)
03-18 11:31:00.888 29447 29447 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-18 11:31:00.888 29447 29447 E AndroidRuntime: FATAL EXCEPTION: main
03-18 11:31:00.888 29447 29447 E AndroidRuntime: Process: my.app, PID: 29447
03-18 11:31:00.888 29447 29447 E AndroidRuntime: java.lang.AssertionError: Unable to create RenderableInstance. 
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.google.ar.sceneform.rendering.RenderableInternalData.buildInstanceData(RenderableInternalData.java:247)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.google.ar.sceneform.rendering.RenderableInstance.prepareForDraw(RenderableInstance.java:285)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.google.ar.sceneform.rendering.Renderer.updateInstances(Renderer.java:596)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.google.ar.sceneform.rendering.Renderer.render(Renderer.java:263)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.google.ar.sceneform.SceneView.doRender(SceneView.java:356)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.google.ar.sceneform.SceneView.doFrameNoRepost(SceneView.java:319)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.google.ar.sceneform.SceneView.doFrame(SceneView.java:301)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:740)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8506)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
03-18 11:31:00.888 29447 29447 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by ThomasGorisse** [comment]
Can you send the crash using the 1.18.5?
The lines numbers doesn't seem to correspond with the last Sceneform  version on your log.

**Comment by cyberhenoch** [comment]
Yes I've added some debug& memory logs so it doesn't match now. In 1.18.5 it happens here:

RenderableInternalData.java:228
```
if (renderableInstance == 0) {
        throw new AssertionError("Unable to create RenderableInstance.");
      }
```

```
java.lang.AssertionError: Unable to create RenderableInstance.
	at com.google.ar.sceneform.rendering.RenderableInternalData.buildInstanceData(RenderableInternalData.java:228)
	at com.google.ar.sceneform.rendering.RenderableInstance.prepareForDraw(RenderableInstance.java:285)
	at com.google.ar.sceneform.rendering.Renderer.updateInstances(Renderer.java:596)
	at com.google.ar.sceneform.rendering.Renderer.render(Renderer.java:263)
	at com.google.ar.sceneform.SceneView.doRender(SceneView.java:356)
	at com.google.ar.sceneform.SceneView.doFrameNoRepost(SceneView.java:319)
	at com.google.ar.sceneform.SceneView.doFrame(SceneView.java:301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by ThomasGorisse** [comment]
It looks like there is an issue with your model.
What format are you using? How many faces does he have? What size is it?
Did you tried the same code with another asset?

**Comment by cyberhenoch** [comment]
Hi
I'm using no custom models. Just ViewRenderables created from a single
android view template. No exceptions while creating them though.

It works perfectly most of the time. But it crashes sometimes, like 1 in a
few thousand tries.

It looks like some kind of memory/cpu/concurrency issue but there is no
error/exception from filament to help debugging, just a zero return value.

+
Regards
Luke

niedz., 21 mar 2021, 10:03 użytkownik Thomas Gorisse <
***@***.***> napisał:

**Comment by ThomasGorisse** [comment]
Can you make the test with the last 1.18.11 version.
Filament and we have made some works on memory and performances.

Thanks

**Comment by cyberhenoch** [comment]
It seems that the error is not happening now for some time in newer versions. Thanks for your great work!

**Comment by dmohnke42** [comment]
We've seen this in version 1.17.1.  I'll build with the updated version and see if it solves the problem.  We encountered the same issue.  It seems to occur when the device is not aimed at the plane.
