### ISSUE TITLE
Can we include sceneform 1.15 in current module ?

### ISSUE THREAD

**Issue by suryanadiminti99** [ThomasGorisse/sceneform-android-sdk#23]
Hi, I am using sceneform latest version. can we use previous gradle version ?
@ThomasGorisse @senthil5053 @vortice3D @RGregat @jthoeny

**Comment by ThomasGorisse** [comment]
What are you talking about precisely?

**Comment by suryanadiminti99** [comment]
What i am saying is , Currently we are using this repository 
[(https://github.com/ThomasGorisse/sceneform-android-sdk)]
. Previous version is 1.15 . So can we merge both versions in same project . or it will throw any conflicts?



![Capture](https://user-images.githubusercontent.com/13411551/112576152-beb72e00-8e17-11eb-91ae-93613283ae73.JPG)

@ThomasGorisse

**Comment by suryanadiminti99** [comment]
If we use previous version my video problem is resolved . That's why i am asking.

**Comment by RGregat** [comment]
If something is not working with the latest version from Thomas, a stacktrace would help alot to find the issue you have.

**Comment by ThomasGorisse** [comment]
@suryanadiminti99 We are waiting for your pull request

**Comment by suryanadiminti99** [comment]
Thankyou @ThomasGorisse
