### ISSUE TITLE
How to do chroma keying

### ISSUE THREAD

**Issue by aseemsalimtvm** [ThomasGorisse/sceneform-android-sdk#25]
When i did chroma keying its crashing

**Comment by suryanadiminti99** [comment]
Chromakey  is not  supported for this version. Google stopped sfb support . Thats why you are getting this issue. 
Please go with this link.  https://github.com/ThomasGorisse/sceneform-android-sdk/issues/21

**Comment by ThomasGorisse** [comment]
The 1.18.8 release solves some Material issues and brings a Video Texture sample
[Release 1.18.8 - Video Texture + SceneView Background](https://github.com/ThomasGorisse/sceneform-android-sdk/releases/tag/v1.18.8)
