### ISSUE TITLE
Depth API disabled

### ISSUE THREAD

**Issue by RGregat** [ThomasGorisse/sceneform-android-sdk#26]
Is there any reason why you disabled the Depth API here https://github.com/ThomasGorisse/sceneform-android-sdk/blob/master/ux/src/main/java/com/google/ar/sceneform/ux/BaseArFragment.java#L401 ?
If I use the old way to set the session config via **getSessionConfiguration** my enabled Depth API get's deactivated in the above mentioned line in the **BaseArFragment** class. 

So this

```java

Config config = getSessionConfiguration(session);

config.setDepthMode(Config.DepthMode.DISABLED);
config.setPlaneFindingMode(Config.PlaneFindingMode.HORIZONTAL_AND_VERTICAL);
config.setFocusMode(Config.FocusMode.AUTO);
```

might be maybe something like this.

```java
Config config = new Config(session);
config.setDepthMode(Config.DepthMode.DISABLED);
config.setPlaneFindingMode(Config.PlaneFindingMode.HORIZONTAL_AND_VERTICAL);
config.setFocusMode(Config.FocusMode.AUTO);

config = getSessionConfiguration(config);
```

**Comment by suryanadiminti99** [comment]
https://github.com/ThomasGorisse/sceneform-android-sdk/issues/21

**Comment by ThomasGorisse** [comment]
Hi @RGregat,

You're true, I disabled Depth mostly because of issues on the plane renderer and detection with the latest ARCore version.
And by the way, Sceneform doesn't handle the Depth Image returned by ARCore.
**If you have something to pull on this part, it's open.**
**I will not develop the Depth Mode on Sceneform** because a new Framework is on his way and handles it very well with a dedicated camera projection material.

I knew I had to make the Session config available so it was the occasion. [Here is the commit](https://github.com/ThomasGorisse/sceneform-android-sdk/commit/7496cfc46ac3a3ab4b385ee1e0b27d7dea423681)
Move to the [snapshot dependency](https://thomasgorisse.github.io/sceneform-android-sdk/dependencies)
and use it like this:
```
arFragment.setOnSessionConfigurationListener((session, config) -> {
    config.setDepthMode(Config.DepthMode.AUTOMATIC);
});
```

**Comment by RGregat** [comment]
Ah yeah this is even better with the interface. 
I use the Depth API only to measure the distance from the camera to the ground, so nothing fancy.

**Comment by sumeshpandit** [comment]
```
@Override
    public void onSessionConfiguration(Session session, Config config) {
  
        if (session.isDepthModeSupported(Config.DepthMode.AUTOMATIC)) {
            config.setDepthMode(Config.DepthMode.AUTOMATIC);
        }
        config.setUpdateMode(Config.UpdateMode.LATEST_CAMERA_IMAGE);
    }
```
I am using depth API but not getting great result (6 out of 10). I have used the above code snippet. Am I doing something wrong or is there another way to do it as you were saying in the above comments that another framework is coming.
@ThomasGorisse  @RGregat

**Comment by RGregat** [comment]
What is your definition of "not great"?

With `config.setDepthMode(Config.DepthMode.AUTOMATIC);` you enable the usage of the DepthPoint Trackable for example. But it doesn't enable occlusion, where it is possible to hide virtual objects behind real objects.
```java
@Override
public void onViewCreated(ArFragment arFragment, ArSceneView arSceneView) {
    // Available modes: DEPTH_OCCLUSION_DISABLED, DEPTH_OCCLUSION_ENABLED
    arSceneView.getCameraStream().setDepthOcclusionMode(CameraStream.DepthOcclusionMode.DEPTH_OCCLUSION_ENABLED);
}
```

You also have to consider that it makes a difference if your Smartphone has a ToF-Sensor or not. And even with a ToF-Sensor you have to consider the environmental conditions. For example bright sunlight, might reduce the quality drastically with a lot of jumps and drifts of placed anchors. 
On the other side you will get on many occasions better results compared to a single RGB camera. Speaken of that, the Depth API is feed mainly by a single RGB camera, because most Smartphones doesn't have a ToF-Sensor!
So yeah, this is only a very rough description what could effect the quality. 
The question ist, what is your use case and what do you want to achieve?

**Comment by sumeshpandit** [comment]
> What is your definition of "not great"?
> 
> With `config.setDepthMode(Config.DepthMode.AUTOMATIC);` you enable the usage of the DepthPoint Trackable for example. But it doesn't enable occlusion, where it is possible to hide virtual objects behind real objects.
> 
> ```java
> @Override
> public void onViewCreated(ArFragment arFragment, ArSceneView arSceneView) {
>     // Available modes: DEPTH_OCCLUSION_DISABLED, DEPTH_OCCLUSION_ENABLED
>     arSceneView.getCameraStream().setDepthOcclusionMode(CameraStream.DepthOcclusionMode.DEPTH_OCCLUSION_ENABLED);
> }
> ```
> 
> You also have to consider that it makes a difference if your Smartphone has a ToF-Sensor or not. And even with a ToF-Sensor you have to consider the environmental conditions. For example bright sunlight, might reduce the quality drastically with a lot of jumps and drifts of placed anchors.
> On the other side you will get on many occasions better results compared to a single RGB camera. Speaken of that, the Depth API is feed mainly by a single RGB camera, because most Smartphones doesn't have a ToF-Sensor!
> So yeah, this is only a very rough description what could effect the quality.
> The question ist, what is your use case and what do you want to achieve?

I am rendering a 3d model and I want to enable depth in it like if there is a table, the model should probably go behind the table depending on the distance, to give a feeling of real presence. I am using a phone with ToF sensor. I am testing this in indoor lighting conditions.

**Comment by ThomasGorisse** [comment]
I don't understand. Is your table a real table or a 3D model?
If it's a 3D, there is no relation with AR depth but more with rendering order/priority and maybe with collision if you want your objects to have physical interrections.

**Comment by sumeshpandit** [comment]
A real table. I want to achieve something like this-   https://redirector.gvt1.com/edgedl/arcore/cat-occlusion.mp4

**Comment by sumeshpandit** [comment]
you made this comment **I will not develop the Depth Mode on Sceneform because a new Framework is on his way and handles it very well with a dedicated camera projection material.**

Can you tell me about this framework?

**Comment by ThomasGorisse** [comment]
Seriously?

Do you only know that you are speaking to real, not paid for that (not even 1$ sponsored) humans here?
You don't participate in any way to this repository and **don't even share your result with others after we have answered you**.

We gratefully share **FREELY** our time for developing and helping people here so please use a little bit of courtesy (_Hi_, _Thanks_, _Please_) before asking.

For your question, just take 5 minutes to search for answers in this repo or the RealityCore one before asking an already multiple time answered question.

**And please stop mentioning spam!!!! We receive a notification each time**

**Comment by sumeshpandit** [comment]
> Seriously?
> 
> Do you only know that you are speaking to real, not paid for that (not even 1$ sponsored) humans here?
> You don't participate in any way to this repository and **don't even share your result with others after we have answered you**.
> 
> We gratefully share **FREELY** our time for developing and helping people here so please use a little bit of courtesy (_Hi_, _Thanks_, _Please_) before asking.
> 
> For your question, just take 5 minutes to search for answers in this repo or the RealityCore one before asking an already multiple time answered question.
> 
> **And please stop mentioning spam!!!! We receive a notification each time**

Chill man!! why you bursting out on me. It's not been even 24 hrs since I asked the question and you expect me to publish the results.  How can you even assume that I would have reached the conclusion so soon.

**Comment by RGregat** [comment]
As Thomas already said, pls take a look to this ARCore sample https://github.com/google-ar/arcore-android-sdk/tree/master/samples/hello_ar_java
It uses a different approach as Sceneform but the result should be similar or in the best case the same.
