### ISSUE TITLE
New fullscreen mode

### ISSUE THREAD

**Issue by grassydragon** [ThomasGorisse/sceneform-android-sdk#33]
Hello, @ThomasGorisse!
The previous fullscreen mode was hiding the action, status and navigation bars and making the activity content fullscreen.
Now only the navigation bar disappears but the activity content is still fullscreen (it's behind the action and status bars as can be seen in the examples in  README.md). https://github.com/ThomasGorisse/sceneform-android-sdk/commit/b2b77ef5a000a70f196682ac2eaee41e1e33c64c
Is it the intended behavior? For me it was the correct fullscreen mode before.
As an improvement I can implement the selection of the mode in BaseARFragment. It will be possible to select between the normal and fullscreen modes. Also, it is possible to migrate to WindowInsetsController

**Comment by ThomasGorisse** [comment]
Hi @grassydragon,

I'm happy to talk about Full Screen mode on Android with someone.

After more than 10 years of Android development, this part is still a complete mystery and every flag modification on the full screen mode is a roll dice upon the toobar and other layouts placement below the status bar depending on the current Android version.
Not related to Sceneform but my solution for other projects is a custom ConstraintLayout which looks for the fitsSystemWindows in every childs in all the hierarchy.
But it's not really applicable to the Sceneform module.

Anyway, here are my answers :

> The previous fullscreen mode was hiding the action, status and navigation bars and making the activity content fullscreen.
> Now only the navigation bar disappears but the activity content is still fullscreen (it's behind the action and status bars as can be seen in the examples in README.md)
For me, the difference between the View.SYSTEM_UI_FLAG_FULLSCREEN are:
1. With = StatusBar hided but StatusBar insets/margin still here and we can't draw behind it (just change the colorPrimaryDark on it)
2. Without = StatusBar visible but can be transparent and no StatusBar top margin
The solution could be to let the View.SYSTEM_UI_FLAG_FULLSCREEN flag present and use the`ViewCompat.setOnApplyWindowInsetsListener()` to remove status bar insets but this could generate wrong behaviors depending on how the `BaseARFragment` is overridden.
 
> As an improvement I can implement the selection of the mode in BaseARFragment. It will be possible to select between the normal and fullscreen modes. Also, it is possible to migrate to WindowInsetsController
It will be great if you can make a pull request and I will check that. Don't forget to check the minSDK > 30 before using the WindowInsetsController

Thanks for your feedback

**Comment by grassydragon** [comment]
Here are examples from Google Pixel 3a with Android 11. In both cases it is possible to put a TextView behind the status bar.

With the View.SYSTEM_UI_FLAG_FULLSCREEN flag:
![Screenshot_20210414-192136](https://user-images.githubusercontent.com/35110066/114756519-7f6b6580-9d63-11eb-96ce-bacd34ee2765.png)
![Screenshot_20210414-192145](https://user-images.githubusercontent.com/35110066/114756522-809c9280-9d63-11eb-8cfb-847a3571210f.png)

Without the View.SYSTEM_UI_FLAG_FULLSCREEN flag:
![Screenshot_20210414-192617](https://user-images.githubusercontent.com/35110066/114756563-8e521800-9d63-11eb-8c8b-e05ad9aec73f.png)

What version of Android should I check?

**Comment by ThomasGorisse** [comment]
Potentially, every API version should be checked since 24.
Are you using `CoordinatorLayout` ?

Here is the result on API 29 :

- **With** View.SYSTEM_UI_FLAG_FULLSCREEN
![image](https://user-images.githubusercontent.com/6597529/114763281-eb010300-9d62-11eb-9479-2c5bcd1c04c1.png)

- **Without** View.SYSTEM_UI_FLAG_FULLSCREEN
![image](https://user-images.githubusercontent.com/6597529/114763134-c1e07280-9d62-11eb-87b5-58c57cb2d6f5.png)

**Comment by grassydragon** [comment]
Actually, I am using the glTF sample from the repository with `FrameLayout`.

Thank you for providing the screenshots, I will try to reproduce the behavior. I think there is a problem with the cutout but there isn't one on the Google Pixel 4.

**Comment by grassydragon** [comment]
Here are examples from Motorola G7 Play with Android 10. This phone has a cutout.

With the View.SYSTEM_UI_FLAG_FULLSCREEN flag:
![Screenshot_20210415-201335](https://user-images.githubusercontent.com/35110066/114915631-75fa0000-9e2c-11eb-9b27-55c6822dd501.png)
![Screenshot_20210415-201407](https://user-images.githubusercontent.com/35110066/114915637-78f4f080-9e2c-11eb-8aac-b34940089b1f.png)

Without the View.SYSTEM_UI_FLAG_FULLSCREEN flag the status bar is transparent and the TextView is behind the cutout.

Unfortunately, I have problems with running AR applications in the emulator on Ubuntu. I will try to do this on Windows.

**Comment by grassydragon** [comment]
Hello, @ThomasGorisse!
I was able to reproduce the problem on the Google Pixel 4 emulator with Android 10. However, there is no such problem on the Google Pixel 3a emulator. As I said earlier it looks like a problem with the cutout. I think that the Google Pixel 4 emulator with Android 10 has a wrong configuration. My friend who has the Google Pixel 4 confirmed that this is not a right behavior.
Let's restore the View.SYSTEM_UI_FLAG_FULLSCREEN flag in order not to break the layout for phones with a real cutout. For cases there this fullscreen mode is not suitable for developers I can add an option for disabling the fullscreen mode so it is possible to set up the fullscreen mode manually.

**Comment by ThomasGorisse** [comment]
Hi @grassydragon,

You have contributor access.
Can you push the modification with the `View.SYSTEM_UI_FLAG_FULLSCREEN` and the `WindowInsetsController` for `Build.VERSION.SDK_INT >= Build.VERSION_CODES.R` ?

Thanks

**Comment by grassydragon** [comment]
Yes, I can. I will test how the window insets controller works.
