### ISSUE TITLE
Memory leak in graphics

### ISSUE THREAD

**Issue by Miao-10k** [ThomasGorisse/sceneform-android-sdk#34]
I am running the gltf sample with a customized model. It seems that the graphics memory is not released after the MainActivity destroyed which can be seen from the profiler. This may lead to out of memory if I start and then destroy the activity several times. 
As mentioned in the issue I opened in filament, I tried to fix this memory problem by adding `Renderer.destroyAllResources()` at the end of `onDestroy()` of BaseArFragment, which will lead to a crash in the function `RenderableInstance.createFilamentAssetModelInstance` when I start the activity again. Do you have any idea about solving the memory problem or why this crash happens after the filament engine destroyed?
![image](https://user-images.githubusercontent.com/32147896/114808430-cc3e5300-9dda-11eb-8b28-c9e4041c0ca2.png)

**Comment by ThomasGorisse** [comment]
Can you clone the repo, try to fix it and make a pull request or put the solution here ?

**Comment by ThomasGorisse** [comment]
Hi @Miao-10k,

Can you try the latest version to check if it brings fixes to your memory leaks ?

Thanks

**Comment by steven-gao** [comment]
@Miao-10k  i met as same crash as you ,i do as you do to release memory use "Renderer.destroyAllResources()" function.
Did you solve that problem
thank for your time

**Comment by steven-gao** [comment]
@ThomasGorisse i use 1.18.11 version，memory is released after activity destory.
thank you very much.

**Comment by steven-gao** [comment]
@ThomasGorisse  could you tell me how do you release memory ?

**Comment by ThomasGorisse** [comment]
You can call the `SceneView.reclaimReleasedResources()`.
It will release rendering resources ready for garbage collection.

**Comment by steven-gao** [comment]
> You can call the `SceneView.reclaimReleasedResources()`.
> It will release rendering resources ready for garbage collection.

but in your demo ,i'm not found where to invoke SceneView.reclaimReleasedResources(),i still not understand how do you release your memory?
