### ISSUE TITLE
 Duplicate class com.google.ar.sceneform.BuildConfig

### ISSUE THREAD

**Issue by andisoer** [ThomasGorisse/sceneform-android-sdk#35]
Hi @ThomasGorisse, thanks for keeping sceneform updated!

I'm using version 1.18.8 and encountered this error while try to run my project

` Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.ar.sceneform.BuildConfig found in modules jetified-core-1.18.8-runtime (com.gorisse.thomas.sceneform:core:1.18.8) and jetified-sceneform-1.18.8-runtime (com.gorisse.thomas.sceneform:sceneform:1.18.8)`

When i downgrade to 1.18.6, everything work fine.

Any solution?

**Comment by ThomasGorisse** [comment]
Please show me your /build.gradle and /app/build.gradle files

**Comment by andisoer** [comment]
> Please show me your /build.gradle and /app/build.gradle files

app/build.gradle

`plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.soerjdev.arsceneformstarter"
        minSdkVersion 24
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        viewBinding = true
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "androidx.core:core-ktx:1.3.2"
    implementation "androidx.appcompat:appcompat:1.2.0"
    implementation "com.google.android.material:material:1.3.0"
    implementation "androidx.constraintlayout:constraintlayout:2.0.4"
    implementation "androidx.fragment:fragment-ktx:1.3.2"

    implementation("com.gorisse.thomas.sceneform:sceneform:1.18.8")

    testImplementation "junit:junit:4.13.2"
    androidTestImplementation "androidx.test.ext:junit:1.1.2"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.3.0"
}`

build.gradle

`// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = "1.4.32"
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.1.3"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

**Comment by andisoer** [comment]
/build.gradle

![carbon (5)](https://user-images.githubusercontent.com/43394528/114842544-24894b00-9e03-11eb-88d7-fe3fb1151a13.png)

/app/build.gradle

![carbon (6)](https://user-images.githubusercontent.com/43394528/114842636-3c60cf00-9e03-11eb-93f0-454e29785965.png)

**Comment by ThomasGorisse** [comment]
Try removing the `jcenter()` and `maven { url 'https://jitpack.io' }`
And add the `mavenCentral()`

**Comment by ThomasGorisse** [comment]
There seems to have an issue with the moving to mavenCentral().
Use this as a temporary fix:
```gradle
implementation("com.gorisse.thomas.sceneform:core:1.18.8")
implementation("com.gorisse.thomas.sceneform:ux:1.18.8")
```
instead of
```gradle
implementation("com.gorisse.thomas.sceneform:sceneform:1.18.8")
```

**Comment by andisoer** [comment]
> There seems to have an issue with the moving to mavenCentral().
> Use this as a temporary fix:
> 
> ```groovy-gradle
> implementation("com.gorisse.thomas.sceneform:core:1.18.8")
> implementation("com.gorisse.thomas.sceneform:ux:1.18.8")
> ```
> 
> instead of
> 
> ```groovy-gradle
> implementation("com.gorisse.thomas.sceneform:sceneform:1.18.8")
> ```

Work now, thanks!

**Comment by andisoer** [comment]
> There seems to have an issue with the moving to mavenCentral().
> Use this as a temporary fix:
> 
> ```groovy-gradle
> implementation("com.gorisse.thomas.sceneform:core:1.18.8")
> implementation("com.gorisse.thomas.sceneform:ux:1.18.8")
> ```
> 
> instead of
> 
> ```groovy-gradle
> implementation("com.gorisse.thomas.sceneform:sceneform:1.18.8")
> ```

Work now, thanks! Is there any estimate time when will the issue with moving to mavenCentral() fix?
