### ISSUE TITLE
Duplicating BuildConfig class

### ISSUE THREAD

**Issue by falcon-group** [ThomasGorisse/sceneform-android-sdk#36]
@ThomasGorisse Good evening, there is an issue when build the dependecy com.gorisse.thomas.sceneform:sceneform:1.18.8.
Stack trace looks like this:
Duplicate class com.google.ar.sceneform.BuildConfig found in modules core-1.18.8-runtime (com.gorisse.thomas.sceneform:core:1.18.8) and sceneform-1.18.8-runtime (com.gorisse.thomas.sceneform:sceneform:1.18.8)

**Comment by andisoer** [comment]
Try to use temporary depedencies as mention at #35
