### ISSUE TITLE
Support for Augmented Images

### ISSUE THREAD

**Issue by andisoer** [ThomasGorisse/sceneform-android-sdk#37]
@ThomasGorisse thanks for keeping update this Scenefrom Android SDK

Is this forked library support with Augmented Image?

thanks!

**Comment by ThomasGorisse** [comment]
Can you make a Pull Request (quite easy to do directly from Android Studio) applying the [v1.15 augmentedimage Sample project](https://github.com/google-ar/sceneform-android-sdk/tree/v1.15.0/samples/augmentedimage) to the last version ?

**Comment by ThomasGorisse** [comment]
Fixed here thanks to @VojtaMaiwald: b6965e0400d160729102df53da71d76aed30b737
