### ISSUE TITLE
Only one texture applied on model that consists of many textures

### ISSUE THREAD

**Issue by VojtaMaiwald** [ThomasGorisse/sceneform-android-sdk#39]
Hello Thomas,
first of all I would like to thank you very much for keeping Sceneform updated and alive. You are doing a wonderful job!

I recently tried to update from version 1.18.6 to 1.18.9 but I faced one issue. My models which are made of many different textures are now displayed completely in one texture. You can see it in the attached pictures below. The only things I change are Sceneform versions in gradle.

Every model is created in Cinema4D and than exported to .glb file.
If I use for example this model:
`https://github.com/google/model-viewer/raw/master/packages/shared-assets/models/Astronaut.glb`
than it works as it should and the textures are shown correctly.

Are there any settings I missed?

You can get my models from here (Fox and Rabbit are shown in attachments):
`https://github.com/VojtaMaiwald/SovinecAR/tree/master/app/src/main/assets`

Thank you in advance!

**For `implementation("com.gorisse.thomas.sceneform:sceneform:1.18.6")` in gradle it looks like this:**
![image](https://user-images.githubusercontent.com/72343092/115288366-a48c1980-a151-11eb-9f0d-dfd73c444000.png)
**For `implementation("com.gorisse.thomas.sceneform:sceneform:1.18.9")` in gradle it looks like this:**
![image](https://user-images.githubusercontent.com/72343092/115288435-b968ad00-a151-11eb-90dd-e6dd1ad5de55.png)

**For `implementation("com.gorisse.thomas.sceneform:sceneform:1.18.6")` in gradle it looks like this:**
![image](https://user-images.githubusercontent.com/72343092/115288310-976f2a80-a151-11eb-978b-52a0a43fa191.png)
**For `implementation("com.gorisse.thomas.sceneform:sceneform:1.18.9")` in gradle it looks like this:**
![image](https://user-images.githubusercontent.com/72343092/115288230-7dcde300-a151-11eb-9b65-c55b1ac71a72.png)

**Comment by ThomasGorisse** [comment]
Thanks for the good and clear report.

**Comment by ThomasGorisse** [comment]
@VojtaMaiwald, I saw all your greats github repositories.
Would you mind making a PullRequest (quite easy directly form AndroidStudio) for an augmented image sample ?
If so, I will give you contributor access.

**Comment by VojtaMaiwald** [comment]
@ThomasGorisse I think that should be possible. Augmented Images feature works quite fine in my app based on your repository. Do you want me to prepare a new sample module?

**Comment by ThomasGorisse** [comment]
That would be great.
I sent you the contributor invite.
Just create a new Pull Request from GitHub or Android Studio. This will automatically create a new temporary branch.
Name the sample augmented-images and try to base it on the same others samples code.

Thanks!

**Comment by ThomasGorisse** [comment]
For the sample scope, it will be more accurate to use .jpg or .png files directly from the asset folder instead of prebuild augmented images database.

**Comment by VojtaMaiwald** [comment]
OK, I will try to do so asap.

**Comment by VojtaMaiwald** [comment]
I created a pull request with the sample. It works on my side but double check it first by yourself please. I added comments to some important parts of the code. Used AR tags you can find in drawable folder so you can display them, print them or place in emulator VirtualScene.

I was trying to get rid of the shadows completely but it doesn't quite seem to work unfortunately....
Feel free to change or add anything, I am not really sure if I my approaches are the best possible and if the project is set up correctly.

This is the result:
![Clipboard01111](https://user-images.githubusercontent.com/72343092/115557548-17aca180-a2b2-11eb-9145-8abbf7bc39ae.png)
