### ISSUE TITLE
Model not displayed (Sceneview-background)

### ISSUE THREAD

**Issue by JooHyun-plask** [ThomasGorisse/sceneform-android-sdk#47]
hi i Referenced sceneview-background example

but application crash when load 3d model(FBX)

my error code is here

![스크린샷 2021-04-27 오후 3 41 51](https://user-images.githubusercontent.com/71476797/116197765-1840ae80-a770-11eb-99e8-bae4ccaf8ca0.png)

and my code here

`    public void renderLocalObject(){
        ModelRenderable.builder()
                .setSource(this, Uri.parse(localModel))
                .setRegistryId(localModel)
                .build()
                .thenAccept(modelRenderable -> {
                    addNodeToScene(modelRenderable);
                })
                .exceptionally(throwable -> {
                    String message = throwable.getMessage();

                    Handler mainHandler = new Handler(Looper.getMainLooper());
                    Runnable myRunnable = (Runnable)(new Runnable(){

                        @Override
                        public void run() {
                            dialog.getBuilder().content(message)
                                    .positiveText("확인")
                                    .canceledOnTouchOutside(false)
                                    .autoDismiss(false)
                                    .onPositive(new MaterialDialog.SingleButtonCallback() {
                                        @Override
                                        public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                            finish();
                                        }
                                    }).show();
                        }
                    });
                    mainHandler.post(myRunnable);
                    return null;
                });
    }`

`    public void addNodeToScene(ModelRenderable model){
        if (mSceneView != null ){
            double y = 0.0;
            TransformationSystem transformationSystem = makeTransformationSystem();
            DragTransformableNode dragTransformableNode = new DragTransformableNode(3.0F, transformationSystem);

            dragTransformableNode.setLookDirection(new Vector3(1.0F, 0.0F, 2.0F));
            dragTransformableNode.setRenderable((Renderable) model);

            
            dragTransformableNode.setLocalScale(new Vector3(2.0F, 2.0F, 2.0F));
            dragTransformableNode.setLocalPosition(new Vector3(0.0F, -1.5F, 0.0F));
            Log.e(TAG, "model default scale : "+dragTransformableNode.getLocalScale().toString());
            Log.e(TAG, "model default position : "+dragTransformableNode.getLocalPosition().toString());

            Objects.requireNonNull(mSceneView.getScene().getSunlight()).setEnabled(true);
            mSceneView.getScene().addChild((Node) dragTransformableNode);

            if (Objects.requireNonNull(dragTransformableNode.getRenderableInstance()).hasAnimations()){
                dragTransformableNode.getRenderableInstance().animate(true).start();
            }

//            if (model.getAnimationData(0) !=null){
//                AnimationData data = model.getAnimationData(0);
//                ModelAnimator animator = new ModelAnimator(data, model);
////                animator.ofAnimationTime(model, 0, 10.0f);
//                animator.setRepeatCount(Animation.INFINITE);
//                animator.start();
//            }
            dragTransformableNode.select();
            mSceneView.getScene().addOnPeekTouchListener(new Scene.OnPeekTouchListener() {
                @Override
                public void onPeekTouch(HitTestResult hitTestResult, MotionEvent motionEvent) {
                    transformationSystem.onTouch(hitTestResult, motionEvent);
                }
            });
        }
    }`

i have no idea

oh sorry localmodel is "dying.sfb" in my assets

**Comment by ThomasGorisse** [comment]
Sceneform is not compatible anymore with SFB format anymore.
Please use a GLB model instead.

**Comment by JooHyun-plask** [comment]
> Sceneform is not compatible anymore with SFB format anymore.
> Please use a GLB model instead.

Thanks you for answer

i changed model(fbx -> glb) and success display model

and i have more question sorry..

how can i record video with background image? 
in this example if i record video only recorded sceneview
please any tips

**Comment by ThomasGorisse** [comment]
Please asks questions in the Discussions section.

You can record the SceneView SurfaceView quite easily but since the background is behind it, I don't know if it will work but you can try recording the parent. Many example are available on the web.
