### ISSUE TITLE
Loading a glTF file will throw inside of Filament and not find the associated bin file.

### ISSUE THREAD

**Issue by imbrig** [ThomasGorisse/sceneform-android-sdk#49]
1. Using the "sample-sceneview-background" demo project add the following gltf and bin files from here (https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedSimple/glTF) to the models folder where the cube.glb file exist.
2. At line 60 of `MainActivity.java` replace `cube.glb` with `RiggedSimple.gltf`
3. Build the project and run.

Observed Results:
Demo crashes with error in Logcat: `com.google.ar.sceneform.samples.sceneviewbackground E/Filament: Unable to load external resource: RiggedSimple0.bin`

Proposed Solution:
Inside of `RenderableInstance.java` in the `createFilamentAssetModelInstance` function, move `renderableData.resourceLoader.asyncBeginLoad(createdAsset);` at line 145 and call that at line 176 replacing `renderableData.resourceLoader.loadResources(createdAsset);` so that all resource files get to be added in the `renderableData.resourceLoader.addResourceData` block above before loading the asset.

Tested with both glb and gltf files, with no found issues so far.

**Comment by ThomasGorisse** [comment]
Hi @imbrig,
Great job !!!
I didn't have a look at the .glTF loading yet.
Can you please make a Pull Request with your modifications ?

I saw your DIY repositories, it seems very interesting. Are you trying to mix AR with a DIY project?

**Comment by imbrig** [comment]
@ThomasGorisse I've created this PR https://github.com/ThomasGorisse/sceneform-android-sdk/pull/54
Yes, you are correct. The 3D asset will either be handled by ARCore or by another AR CV library which updates nodes on the asset through matrices.
Currently I'm using Filament (and a bunch of custom code to manage the entities) with my project but there is a need to use a scene graph on top of it and your Sceneform project is a good candidate. This would clean up my fork of Filament, by moving the custom behavior of the updates to the scene graph library.

**Comment by ThomasGorisse** [comment]
I will try to have a look at the PR soon. Thanks a lot.

> Yes, you are correct. The 3D asset will either be handled by ARCore or by another AR CV library which updates nodes on the asset through matrices.

What do you mean by this ? I'm not sure to understand. AR CV library ?

> Currently I'm using Filament (and a bunch of custom code to manage the entities) with my project but there is a need to use a scene graph on top of it and your Sceneform project is a good candidate. This would clean up my fork of Filament, by moving the custom behavior of the updates to the scene graph library.

I will definitely have a look at your repo since it's exactly what I'm currently working on. It will be a new framework which is not completely a node based implementation but not even an `int entity` and `int manager.entityInstance` extend.
It's in Kotlin and I focused a lot on the documentation part before completing some missing todo codes.
If you are interested, you can participate or just have a look first.
I will tell you when it's online.

**Comment by imbrig** [comment]
@ThomasGorisse Apologies for the vagueness, we are currently working on https://apps.apple.com/us/app/swerve-body-ar-effects/id1531999916 for android. Our face and body tracking sdk essentially works similar to ARCore (without any need for arcore or we can combine both), where we receive anchor points which are used to modify nodes on the assets.
Your fork of Sceneform seems to do what we need without having to make heavy changes to Filament, currently a private experimental fork but the goal is to use a minimally modified Filament.

**Comment by imbrig** [comment]
@ThomasGorisse It's turning out that Sceneform might not have all of the core functionality that we need. I was hoping that it would have a 1 to 1 node to Filament entity relationship, mirroring the glTF file since we need to manipulate the nodes and joints individually.
From what I've seen, Sceneform loads the glTF and then it's all applied to one node with the Renderable initialing the call to load the asset through filament. Only the RenderableInstance has any knowledge of the entity.

> It will be a new framework which is not completely a node based implementation but not even an int entity and int manager.entityInstance extend.
> It's in Kotlin and I focused a lot on the documentation part before completing some missing todo codes.
> If you are interested, you can participate or just have a look first.

I am very interested in your scene project and seeing if it's right for my current project.
I can be reached at brigido@image-metrics.com. Thank you.
