### ISSUE TITLE
How to Render GlSurfaceview

### ISSUE THREAD

**Issue by aseemsalimtvm** [ThomasGorisse/sceneform-android-sdk#55]
I have created a 3d model by using the GLSurfaceview (OpenGL) and rendered it by using the ViewRenderable but it does not work properly, could you please help me?

**Comment by ThomasGorisse** [comment]
What are trying to achieve exactly ?

**Comment by aseemsalimtvm** [comment]
I have a rubik's cube model i have rendered and its working perfectly in GLSurfaceview, i want to implement that model in AR, but when i did it through the ViewRendarable it not working perfectly , the model support rendereing of Rubik's Cube up to 7x7x7, i want to implement that in AR, currently i am developing an GLB with blender and some action , i have done 2x2x2 rubiks cube but when its come to higer order it very difficult create all the action, Thats why i am thinking to implement already available opengl model to AR

**Comment by aseemsalimtvm** [comment]
the app i have developed currently https://play.google.com/store/apps/details?id=com.aseemsalim.cubecipher i want to implement AR in this app

**Comment by ThomasGorisse** [comment]
Please use the Discussions part if it's not bug related.
If you want to use your GLES code you should definitely go directly to ARCore and use the corresponding SurfaceView without using Sceneform.
If you want a glTF version, what is precisely your question ?

**Comment by aseemsalimtvm** [comment]
ok
