### ISSUE TITLE
Gls model is not visible on camera screen 

### ISSUE THREAD

**Issue by Uttan** [ThomasGorisse/sceneform-android-sdk#6]
I have tried to give  like this as per your sample 

pointy4Cursor.material.setFloat4("baseColorFactor", Color(1F,1F,1F,1F)) 

but its throwing the exception

**Code snippet:**

 ModelRenderable.builder()
                .setSource(context, Uri.parse("pointy4Cursor.gls"))
                .build()
                .setIsFilamentGltf(true)
                .thenAccept { renderable ->
                    pointy4Cursor = renderable
                    **pointy4Cursor.material.setFloat4("baseColorFactor", Color(1F,1F,1F,1F))**
                }
                .exceptionally {
                    Log.e(TAG, "unable to load renderable pointy4Cursor")
                    val toast = Toast.makeText(context, "Unable to load renderable dkdkjd", Toast.LENGTH_LONG)
                    toast.setGravity(Gravity.CENTER, 0, 0)
                    toast.show()
                    null
                }

Also i tried to change the gls color with blender and used. But i couldn't
 able to see the model in the camera screen. model is always invisible not sure what is happening please help

**Comment by ThomasGorisse** [comment]
What is your gls file format ?
Please use glb instead.
Inside blender : File>Export>glTF2.0 and select the .glb file format.
Sceneform might not recognize your file extension.

**Comment by Uttan** [comment]
Yes i am using glb file format , but when i try to give material in run time its crashing, show submesh count issue. Please help
ModelRenderable.builder()
                    .setSource(context, Uri.parse("redMarker.glb"))
                    .setIsFilamentGltf(true)
                    .build()
                    .thenAccept { renderable ->
                        pointy4Cursor = renderable
                    }
                    .exceptionally {
                        Log.e(TAG, "unable to load renderable pointy4Cursor  - " + it.toString())
                        val toast = Toast.makeText(context, "Unable to load renderable new model 6", Toast.LENGTH_LONG)
                        toast.setGravity(Gravity.CENTER, 0, 0)
                        toast.show()
                        null
                    },

 MaterialFactory.makeOpaqueWithColor(context, Color(context.getColor(R.color.colorSecondary)))
                    .thenAccept {
                        navaPink = it
                    }
                    .exceptionally {
                        Log.e(TAG, "unable to load material navaPink")
                        val toast = Toast.makeText(context, "Unable to load material", Toast.LENGTH_LONG)
                        toast.setGravity(Gravity.CENTER, 0, 0)
                        toast.show()
                        null
                    },

 pointy4Cursor.material = navaPink // It's throwing exception as define above. 

**"java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: submeshIndex (0) is out of range. It must be less than the submeshCount (0)"**

**Comment by ThomasGorisse** [comment]
Can you send your glb file ?

**Comment by Uttan** [comment]
[redMarker.glb.zip](https://github.com/ThomasGorisse/sceneform-android-sdk/files/6082027/redMarker.glb.zip)

**Comment by ThomasGorisse** [comment]
Fixed here: 5c2f6ce24e2cc88490f065e53cf78eada8f0cc7a
