### ISSUE TITLE
SetFocusMode doesn't work

### ISSUE THREAD

**Issue by caiocs** [ThomasGorisse/sceneform-android-sdk#65]
Hi,

I tested the example augmented-images and added the config.setFocusMode(Config.FocusMode.AUTO) on the method setupSession(), and the focus doesn't work.

**Comment by ThomasGorisse** [comment]
`Config.FocusMode.AUTO` is used by default.
Please use the `setOnSessionConfigurationListener` instead of `setOnSessionInitializationListener`.
Augmented Images Sample has been updated. Clone the latest version to see changes.
