### ISSUE TITLE
Runtime model loading

### ISSUE THREAD

**Issue by Methew5** [ThomasGorisse/sceneform-android-sdk#66]
Can I load my model at runtime if it's not glb, but dae for example or something else?

**Comment by ThomasGorisse** [comment]
Only glTF format is supported by Sceneform. You must convert your file first.

**Comment by Methew5** [comment]
> Only glTF format is supported by Sceneform. You must convert your file first.

Maybe there are any libraries for converting models to glTF format at runtime?

**Comment by grassydragon** [comment]
Alternatively, it is possible to use a separate library for loading the model data and creating the renderable definition yourself. This way you can control the supported features of the model format if the conversion to glTF doesn't work perfectly.

**Comment by Methew5** [comment]
> Alternatively, it is possible to use a separate library for loading the model data and creating the renderable definition yourself. This way you can control the supported features of the model format if the conversion to glTF doesn't work perfectly.

Can you recommend one of these kind of libraries?

**Comment by grassydragon** [comment]
I've used the [Assimp](https://github.com/assimp/assimp) library in C++ on PC. It supports many formats, however, there are no bindings for Java. You can take a look at this Kotlin port: https://github.com/kotlin-graphics/assimp
