### ISSUE TITLE
[question] Some models being rendered extremely large

### ISSUE THREAD

**Issue by akshatbahety** [ThomasGorisse/sceneform-android-sdk#67]
Hey @ThomasGorisse  thanks for maintaining the scene form SDK this library has been a life saver.

I just wanted to know if there is a known issue about some models being rendered in extremely huge sizes and some being rendered perfectly well.

https://sketchfab.com/3d-models/gladiador-874fc7e11d674f51a4dc2082d29c9b9a - This renders Perfectly and the size can be adjusted

https://poly.google.com/view/75WQH5E29tF  - This renders in extreme size I haven't been able to see the complete model and for some reason it makes the model extremely difficult to resize

https://glb-packer.glitch.me/ - I am using this to convert the models from GLTF to GLB

And again thanks a lot for the library.

**Comment by ThomasGorisse** [comment]
Hi @akshatbahety,

Actually, the problem come with your plane that has an enormous size (181 meters) has you can see in the transform panel:
![image](https://user-images.githubusercontent.com/6597529/118984859-37e98200-b97e-11eb-9d0d-9171d32cc0c1.png) 
Comparing to the gladiator asset which has a "normal" height of 2.03 meters
![image](https://user-images.githubusercontent.com/6597529/118985618-e1c90e80-b97e-11eb-8645-a6aa0f71fde4.png)

You should definitely consider using Blender to reduce it size.
Just change the desired size on the same panel and export it again to glb.

**Comment by akshatbahety** [comment]
Thanks a lot
