### ISSUE TITLE
applying material at runtime

### ISSUE THREAD

**Issue by Schlewinow** [ThomasGorisse/sceneform-android-sdk#73]
The following issue is currently a major problem in our project.
To play videos on textures, we need to apply a special material that supports external textures.
The material is pre-compiled via the matc-tool in the correct version and provided as Android resource, as seen in the code example.
The renderable is a loaded GLB model and successfully displayed in the scene.

```
Material.builder()
   .setSource(getContext(), R.raw.video_material)
   .build()
   .thenAccept(material -> {
      getRenderable().setMaterial(material);
      material.setExternalTexture("videoTexture", videoTexture);
   })
   .exceptionally(throwable ->  {
      throwable.printStackTrace();
      return null;
   });
```

However, the new material is not applied.
The visuals of the rendered model don't change at all.
No Exception or other error occurs.
It seems the material change by **setMaterial()** is simply ignored.

How can materials be set on renderables at runtime?

Note: We used a similiar approach in older Sceneform-versions by Google, but there the material was set in the SFA/SFB-import-process in build.gradle, so we never had to change materials at runtime.
I don't see a way to change the material of GLBs in the same way. Or is that possible instead?

Tested on version 1.18.11.

**Comment by ThomasGorisse** [comment]
See the video-texture sample

**Comment by ThomasGorisse** [comment]
You must apply the material to the ‘node.getRenderableInstance()‘ not to the model.

**Comment by Schlewinow** [comment]
Ahh, thanks, that did the trick.
So, just for info, what is the difference between a renderable and the renderableInstance on a node?
Does the node create a copy of the renderable when it is applied?

**Comment by ThomasGorisse** [comment]
‘RenderableInstance’ is like its name says : an ‘Instance‘ = no duplicate gltf parsing = Runtime costs minimized in a consuming context.
