### ISSUE TITLE
Integration with react-native

### ISSUE THREAD

**Issue by cristianocca** [ThomasGorisse/sceneform-android-sdk#80]
I'm wondering if this can be integrated with react-native apps.  Looking at the samples, the usage requires a whole new activity.  Can this be used within a custom implemented view/surface? React-native is single-activity, so it wouldn't be possible to use this within a react-native view.

**Comment by ThomasGorisse** [comment]
I'm not a react-native expert but that should be possible. I don't know if it's possible to add custom views in React-native but you could try to override the ARSceneView. You can see what you will have to include in your extension class by having a look at the ARFragment.
Also have a look at this issue : https://github.com/google/filament/issues/4112

**Comment by cristianoccazinsp** [comment]
That’s right, implementing a custom view is what I need. 

I’m basically building an AR measure lib. I have it done for iOS already, and I’m looking for an easy way to implement a custom view for android as well but so far everything seems to involve OpenGL and low level programming. This sdk seems like a close enough match to iOS ARKit sdk which is very user friendly.

Thanks!
