### ISSUE TITLE
Can only change to an animation with a higher index

### ISSUE THREAD

**Issue by Knotworking** [ThomasGorisse/sceneform-android-sdk#87]
I have implemented a `.glb` model that contains multiple animations and can display it in a scene.

I am able to set the animations with this code:
```kotlin
animator?.cancel
animator = ModelAnimator.ofAnimation(renderableInstance, animationIndex).apply {
    start()
}
```
`animationIndex` is the desired index of the animation I want to play.

I have noticed that this code only works if the new `animationIndex` is greater than the previous one. If I try and run this code with a lower `animationIndex`, then the current (higher index) animation keeps playing.

Perhaps it's an indicator of something that `autoCancel` only cancels animations of the same index.

I have tried:
- debugging this myself to get more information, but the returned `ObjectAnimator` seems to be correct.
- Holding separate references to the different `ObjectAnimators` (for each action).
- Setting animations based on names, but this behaves the same as using the index.

Just let me know if I can provide any more information to help reproduce the issue. And thank you for continuing the sceneform project.

**Comment by ThomasGorisse** [comment]
Hi,

Can you provide your .glb and .blend if made from it?

**Comment by Knotworking** [comment]
Yes of course [cat.zip](https://github.com/ThomasGorisse/sceneform-android-sdk/files/6667614/cat.zip)

You'll notice in the blender file that all of the actions have been doubled. I was experiencing strange behaviour before I stumbled upon this ugly hack, that seemed to work. I was checking my .glb files with https://gltf-viewer.donmccurdy.com/ , and both in this webtool and in sceneform the actions aren't doubled and seem to play correctly individually.

**Comment by ThomasGorisse** [comment]
Ok, I figured out what was happening.

I fixed your issue and will soon commit it.

I can confirm that you have to call the `animator?.cancel()` since the auto cancel will work only if you start a new ModelAnimator with the same index.

Thanks for your feedback.

**Comment by ThomasGorisse** [comment]
Can you make the test with the master version?

**Comment by Knotworking** [comment]
Yes I can confirm the latest master version works 👍 

As a side note, I tried using jitpack to get the master branch dependency with:
`implementation 'com.github.thomasgorisse:sceneform-android-sdk:master-SNAPSHOT'`

However I couldn't get it to work, so just built it locally.

Thanks for looking into this issue 👏

**Comment by kustraslawomir** [comment]
@ThomasGorisse should it be resolved in 1.20.2?

I have the same issue with the example [sample-ar-model-viewer], also I'm unable to switch between animations on my project.

I can provide You with a sample project with .glb file and code to test it. I can record the video for You if You need it. Thank you

**Comment by ThomasGorisse** [comment]
Did you try to test your model on a Gltf Viewer?
Are you animations listed there?

**Comment by kustraslawomir** [comment]
Yes :) 
![image](https://user-images.githubusercontent.com/16974890/145817206-89057f52-fc16-4d43-902c-9cafd5b169e6.png)
Also getAnimationNames() return [Farewell, Greeting, Idle, No, Pointing, Talking, Yes]

**Comment by kustraslawomir** [comment]
Blender:
![image](https://user-images.githubusercontent.com/16974890/145817588-5a620200-458c-4456-a32d-766730f05afa.png)

**Comment by kustraslawomir** [comment]
https://user-images.githubusercontent.com/16974890/145818494-893370fc-bf4b-4937-b161-bf4169801576.mp4

You can Track the queue I'm running the animations. Incrementing works just fine, but I can go back for example from Pointing to Greeting.

**Comment by kustraslawomir** [comment]
Code snippet: 
`  private fun displayDebugAnimationList(arCharacter: RenderableInstance) {

        val availableAnimations: List<String> =
            arCharacter.animationNames

        Log.d("Animations", availableAnimations.toString())
        debugButton.setOnClickListener {
            val adapter = ArrayAdapter<String>(
                requireContext(),
                android.R.layout.simple_spinner_dropdown_item,
                availableAnimations
            )
            AlertDialog.Builder(requireContext())
                .setSingleChoiceItems(adapter, 0) { dialogInterface, index ->
                    Toast.makeText(
                        requireContext(),
                        "set animation: ${availableAnimations[index]} index: $index from: ${availableAnimations.toString()}",
                        Toast.LENGTH_LONG
                    ).show()
                    arCharacter.animate(index).start()
                    dialogInterface?.cancel()
                }
                .create()
                .show()
        }
    }`

**Comment by kustraslawomir** [comment]
Also, I'm on:

```
git pull origin master
From https://github.com/SceneView/sceneform-android
 * branch            master     -> FETCH_HEAD
Already up to date.

```

**Comment by kustraslawomir** [comment]
**Ok @ThomasGorisse I think It's because I didn't call .cancel() on ObjectAnimator...** 

```
modelAnimator?.cancel()
                    modelAnimator = ModelAnimator.ofAnimation(arCharacter, index).apply {
                        start()
                    }
```

With this change, it's working and I can go to the previous animation. Thanks again mate! <3

**Comment by ThomasGorisse** [comment]
Great!
I'm curious. Could you provide a screen record just to see what it looks like?

**Comment by kustraslawomir** [comment]
Now I can switch from 0->1->2->1->0. 
https://user-images.githubusercontent.com/16974890/145821470-cad80459-c8db-4322-bb50-1ca40cab393c.mp4
Thanks
