### ISSUE TITLE
App Crashes When i added new release 

### ISSUE THREAD

**Issue by suryanadiminti99** [ThomasGorisse/sceneform-android-sdk#92]
Unable to start activity ComponentInfo{com.plugxr.docomo/com.plugxr.cloudanchors.CreateAchor.ArActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.ar.sceneform.ArSceneView com.google.ar.sceneform.ux.ArFragment.getArSceneView()' on a null object reference

Any one please help me out .

**Comment by suryanadiminti99** [comment]
Actually that issue was cleared . But onUpdate method not called . 

`try {
                arFragment.getArSceneView().getScene().addOnUpdateListener(this);
            }catch (Exception e){
                e.printStackTrace();
            }`

**Comment by ThomasGorisse** [comment]
Make sure to access the ’Fragment.arScene’ on the ’onViewCreated()’

**Comment by suryanadiminti99** [comment]
> Make sure to access the ’Fragment.arScene’ on the ’onViewCreated()’

arFragment.getArSceneView().getScene().addOnUpdateListener(new Scene.OnUpdateListener() {
            @Override
            public void onUpdate(FrameTime frameTime) {
                Log.v("SURYA","CAME");
            }
        });


I implemented like this . Thankyou verymuch.
